//
//  GHAttachment.h
//  Gentlehood
//
//  Created by Anthony Shoumikhin on 2013-09-19.
//  Copyright (c) 2013 Anthony Shoumikhin. All rights reserved.
//

//  Autogenerated by mogenerator and changed

#import "GHAttachment.h"

//==============================================================================
@implementation GHAttachment
//------------------------------------------------------------------------------
+ (RKEntityMapping *)mapping
{
    static RKEntityMapping *mapping;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^
    {
        mapping = [RKEntityMapping mappingForEntityForName:NSStringFromClass(self.class) inManagedObjectStore:RKManagedObjectStore.defaultStore];
        [mapping addAttributeMappingsFromArray:@[@"title", @"url"]];
        [mapping addAttributeMappingsFromDictionary:@{@"id":@"identifier", @"mime_type":@"mime"}];
        mapping.identificationAttributes = @[@"identifier"];
    });

    return mapping;
}
//------------------------------------------------------------------------------
@end
//==============================================================================
