//
//  GHAttachment.h
//  Gentlehood
//
//  Created by Anthony Shoumikhin on 2013-09-19.
//  Copyright (c) 2013 Anthony Shoumikhin. All rights reserved.
//

//  Autogenerated by mogenerator and changed

#import "_GHAttachment.h"

@interface GHAttachment : _GHAttachment

+ (RKEntityMapping *)mapping;

@end
