//
//  GHCategory.h
//  Gentlehood
//
//  Created by Anthony Shoumikhin on 2013-08-06.
//  Copyright (c) 2013 Anthony Shoumikhin. All rights reserved.
//

//  Autogenerated by mogenerator and changed

#import "GHCategory.h"

//==============================================================================
@implementation GHCategory
//------------------------------------------------------------------------------
+ (RKEntityMapping *)mapping
{
    static RKEntityMapping *mapping;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^
    {
        mapping = [RKEntityMapping mappingForEntityForName:NSStringFromClass(self.class) inManagedObjectStore:RKManagedObjectStore.defaultStore];
        [mapping addAttributeMappingsFromDictionary:@{@"id":@"identifier", @"post_count":@"postCount"}];
        mapping.identificationAttributes = @[@"identifier"];
    });

    return mapping;
}
//------------------------------------------------------------------------------
@end
//==============================================================================
