//
//  GHCategory.h
//  Gentlehood
//
//  Created by Anthony Shoumikhin on 2013-08-06.
//  Copyright (c) 2013 Anthony Shoumikhin. All rights reserved.
//

//  Autogenerated by mogenerator and changed

#import "GHPost.h"

//==============================================================================
@implementation GHPost
//------------------------------------------------------------------------------
+ (RKEntityMapping *)mapping
{
    static RKEntityMapping *mapping;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^
    {
        mapping = [RKEntityMapping mappingForEntityForName:NSStringFromClass(self.class) inManagedObjectStore:RKManagedObjectStore.defaultStore];
        [mapping addAttributeMappingsFromArray:@[@"content", @"date", @"title", @"url"]];
        [mapping addAttributeMappingsFromDictionary:@{@"id":@"identifier"}];
        [mapping addRelationshipMappingWithSourceKeyPath:@"categories" mapping:GHCategory.mapping];
        [mapping addRelationshipMappingWithSourceKeyPath:@"attachments" mapping:GHAttachment.mapping];
        mapping.identificationAttributes = @[@"identifier"];
    });

    return mapping;
}
//------------------------------------------------------------------------------
@end
//==============================================================================