//
//  GHCategory.h
//  Gentlehood
//
//  Created by Anthony Shoumikhin on 2013-08-06.
//  Copyright (c) 2013 Anthony Shoumikhin. All rights reserved.
//

//  Autogenerated by mogenerator and changed

#import "_GHPost.h"

@interface GHPost : _GHPost

+ (RKEntityMapping *)mapping;

@end
